import {
  IconBrandGithub,
  IconBrandX,
  IconHome,
  IconUserCircle,
  IconTerminal2,
  IconFile,
  IconMail,
} from "@tabler/icons-react";
import { data } from "autoprefixer";

export const links = [
  {
    title: "Home",
    icon: <IconHome className="h-full w-full" />,
    href: "/",
  },

  {
    title: "Projects",
    icon: <IconTerminal2 className="h-full w-full" />,
    href: "/projects",
  },
  {
    title: "About",
    icon: <IconUserCircle className="h-full w-full" />,
    href: "/about",
  },
  {
    title: "Resume",
    icon: <IconFile className="h-full w-full" />,
    href: "/resume",
  },

  // {
  //   title: "Twitter",
  //   icon: <IconBrandX className="h-full w-full" />,
  //   href: "#",
  // },
  {
    title: "GitHub",
    icon: <IconBrandGithub className="h-full w-full" />,
    href: "https://github.com/Gowtham242529",
  },
];

export const iconCloudIcons = [
  "typescript",
  "javascript",
  "dart",
  "java",
  "react",
  "flutter",
  "android",
  "html5",
  "css3",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
];

export const words = [
  {
    text: "Hi ",
    className: "text-3xl font-extrabold sm:text-6xl text-primary",
  },
  {
    text: "it's ",
    className: "text-3xl font-extrabold sm:text-6xl text-primary",
  },
  {
    text: " Gowtham!",
    className:
      "text-3xl font-extrabold sm:text-6xl text-blue-500 dark:text-blue-500",
  },
];

export const mailDetails = {
  title: "Email",
  link: "mailto:nandavarapugowtham3669@example.com",
  icon: <IconMail className="h-full w-full" />,
  text: "Say Hii!",
};

export const resumeDownloadDetails = {
  title: "Resume",
  link: "/Nandavarapu Gowtham Resume.pdf",
  icon: <IconFile className="h-full w-full" />,
  text: "Resume",
};

export const skillsData = [
  {
    name: "Javascript",
    id: "javascript",
    category: "Languages",
    level: "advanced",
    mostUsed: true,
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    name: "Typescript",
    id: "typescript",
    category: "Languages",
    level: "learning",
    href: "https://www.typescriptlang.org/",
  },
  {
    name: "React",
    id: "react",
    category: "Web Dev",
    field: "Frontend",
    level: "advanced",
    mostUsed: true,
    href: "https://react.dev/",
  },
  {
    name: "Next.js",
    id: "nextjs",
    category: "Web Dev",
    field: "Fullstack",
    subfield: "Frameworks",
    level: "advanced",
    // mostUsed: true,
    href: "https://nextjs.org/",
  },
  {
    name: "Tailwind",
    id: "tailwind",
    category: "Web Dev",
    field: "Frontend",
    subfield: "Styling",
    level: "advanced",
    mostUsed: true,
    href: "https://tailwindcss.com/",
  },
  //   {
  //     name: "Fiber",
  //     id: "fiber",
  //     category: "Web Dev",
  //     field: "Backend",
  //     level: "learning",
  //   },
  {
    name: "ShadCN",
    id: "shadcn",
    category: "Web Dev",
    field: "Frontend",
    subfield: "Styling",
    level: "advanced",
    mostUsed: true,
    href: "https://ui.shadcn.com/",
  },
  {
    name: "HTML",
    id: "html",
    category: "Web Dev",
    field: "Frontend",
    subfield: "Styling",
    level: "advanced",
    href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    name: "CSS",
    id: "css",
    category: "Web Dev",
    field: "Frontend",
    subfield: "Styling",
    level: "advanced",
    href: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  // {
  //   name: 'Prisma',
  //   id: 'prisma',
  //   category: 'Web Dev',
  //   field: 'Backend',
  //   subfield: 'ORM',
  //   level: 'advanced',
  // },
  {
    name: "OpenAI",
    id: "openai",
    category: "AI & Data Science",
    field: "AI",
    description: "GPTs, Whisper",
    level: "familiar",
    mostUsed: true,
    href: "https://openai.com/",
  },
  // {
  //   name: 'LangChain',
  //   id: 'langchain',
  //   category: 'AI & Data Science',
  //   field: 'AI',
  //   subfield: 'Frameworks',
  //   level: 'familiar',
  // },
  {
    name: "Python",
    id: "python",
    category: "Languages",
    level: "learning",
    href: "https://www.python.org/",
  },
  {
    name: "C Lang",
    id: "clang",
    category: "Languages",
    level: "familiar",
    href: "https://www.w3schools.com/c/c_intro.php",
  },
  {
    name: "Node.js",
    id: "nodejs",
    category: "Web Dev",
    field: "Backend",
    level: "familiar",
    mostUsed: true,
    href: "https://nodejs.org/en/about/",
  },
  // {
  //   name: 'Fast API',
  //   id: 'fastapi',
  //   category: 'Web Dev',
  //   field: 'Backend',
  //   level: 'familiar',
  // },
  // {
  //   name: 'Django',
  //   id: 'django',
  //   category: 'Web Dev',
  //   field: 'Backend',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Flask',
  //   id: 'flask',
  //   category: 'Web Dev',
  //   field: 'Backend',
  //   level: 'advanced',
  // },
  {
    name: "Docker",
    id: "docker",
    category: "DevOps & Tools",
    field: "Containers",
    level: "learning",
    href: "https://www.docker.com/",
  },
  {
    name: "AWS",
    id: "aws",
    category: "DevOps & Tools",
    field: "Cloud Providers",
    level: "advanced",
    href: "https://aws.amazon.com/",
  },
  {
    name: "Azure",
    id: "azure",
    category: "DevOps & Tools",
    field: "Cloud Providers",
    level: "advanced",
    href: "https://azure.microsoft.com/en-in",
  },
  {
    name: "Git",
    id: "git",
    category: "DevOps & Tools",
    field: "Source Control",
    level: "advanced",
    mostUsed: true,
    href: "https://git-scm.com/",
  },
  {
    name: "Github",
    id: "github",
    category: "DevOps & Tools",
    field: "Source Control",
    level: "advanced",
    href: "https://github.com/",
  },
  {
    name: "Azure DevOps",
    id: "azuredevops",
    category: "DevOps & Tools",
    field: "Source Control",
    level: "advanced",
    href: "https://docs.microsoft.com/en-us/azure/devops/",
  },
  {
    name: "Bash",
    id: "bash",
    category: "DevOps & Tools",
    field: "Shell",
    level: "learning",
    href: "https://www.gnu.org/software/bash/",
  },
  {
    name: "Powershell",
    id: "powershell",
    category: "DevOps & Tools",
    field: "Shell",
    level: "learning",
    href: "https://learn.microsoft.com/en-us/powershell/",
  },
  {
    name: "Linux",
    id: "linux",
    category: "DevOps & Tools",
    field: "OS",
    level: "advanced",
    href: "https://www.linux.com/",
  },
  {
    name: "MongoDB",
    id: "mongodb",
    category: "Web Dev",
    field: "Backend",
    subfield: "Databases",
    mostUsed: true,
    level: "advanced",
    href: "https://www.mongodb.com/",
  },
  {
    name: "MSSQL",
    id: "mssql",
    category: "Web Dev",
    field: "Backend",
    subfield: "Databases",
    level: "advanced",
    mostUsed: true,
    href: "https://www.microsoft.com/en-us/sql-server/sql-server-2019",
  },
  {
    name: "PostgreSQL",
    id: "postgres",
    category: "Web Dev",
    field: "Backend",
    subfield: "Databases",
    level: "advanced",
    href: "https://www.postgresql.org/",
  },
  {
    name: "MySQL",
    id: "mysql",
    category: "Web Dev",
    field: "Backend",
    subfield: "Databases",
    level: "advanced",
    href: "https://www.mysql.com/",
  },
  {
    name: "Redis",
    id: "redis",
    category: "Web Dev",
    field: "Backend",
    subfield: "Databases",
    level: "advanced",
    href: "https://redis.io/",
  },
  {
    name: "Bootstrap",
    id: "bootstrap",
    category: "Web Dev",
    field: "Frontend",
    subfield: "Styling",
    level: "advanced",
    href: "https://getbootstrap.com/",
  },
  {
    name: "Pandas",
    id: "pandas",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Analytics",
    level: "advanced",
    href: "https://pandas.pydata.org/",
  },
  {
    name: "Numpy",
    id: "numpy",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Analytics",
    level: "advanced",
    href: "https://numpy.org/",
  },
  {
    name: "Anaconda",
    id: "anaconda",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Tools",
    level: "advanced",
    href: "https://anaconda.org/",
  },
  {
    name: "Jupyter",
    id: "jupyter",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Tools",
    level: "advanced",
    href: "https://jupyter.org/",
  },
  {
    name: "Matplotlib",
    id: "matplotlib",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Visualization",
    level: "advanced",
    href: "https://matplotlib.org/",
  },
  {
    name: "Plotly",
    id: "plotly",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Visualization",
    level: "advanced",
    href: "https://plotly.com/",
  },
  {
    name: "Seaborn",
    id: "seaborn",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Visualization",
    level: "learning",
    href: "https://seaborn.pydata.org/",
  },
  {
    name: "Scikit-learn",
    id: "scikitlearn",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "ML",
    level: "learning",
    href: "https://scikit-learn.org/",
  },
  {
    name: "Postman",
    id: "postman",
    category: "DevOps & Tools",
    field: "Tools",
    level: "advanced",
    mostUsed: true,
    href: "https://www.postman.com/",
  },
  // {
  //   name: 'DataDog',
  //   id: 'datadog',
  //   category: 'DevOps & Tools',
  //   field: 'Analytics',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Umami',
  //   id: 'umami',
  //   category: 'DevOps & Tools',
  //   field: 'Analytics',
  //   level: 'advanced',
  // },
  {
    name: "PowerBI",
    id: "powerbi",
    category: "AI & Data Science",
    field: "Data Science",
    subfield: "Visualization",
    level: "advanced",
    href: "https://powerbi.microsoft.com/en-us/",
  },
  // {
  //   name: 'Celery',
  //   id: 'celery',
  //   category: 'Web Dev',
  //   field: 'Backend',
  //   level: 'advanced',
  // },
  {
    name: "NGINX",
    id: "nginx",
    category: "Web Dev",
    field: "Backend",
    level: "advanced",
    href: "https://www.nginx.com/",
  },
  {
    name: "Vercel",
    id: "vercel",
    category: "DevOps & Tools",
    field: "Cloud Providers",
    level: "advanced",
    href: "https://vercel.com/",
  },
  // {
  //   name: 'VLLM',
  //   id: 'vllm',
  //   category: 'AI & Data Science',
  //   field: 'AI',
  //   subfield: 'Frameworks',
  //   level: 'advanced',
  // },
  // {
  //   name: 'OpenSource LLMs, Mistral, LLAMA, Vicuna',
  //   id: 'mistral',
  //   category: 'AI & Data Science',
  //   field: 'AI',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Streamlit',
  //   id: 'streamlit',
  //   category: 'AI & Data Science',
  //   field: 'Prototyping',
  //   level: 'advanced',
  // },
  {
    name: "Gradio",
    id: "gradio",
    category: "AI & Data Science",
    field: "Prototyping",
    level: "learning",
    href: "https://gradio.app/",
  },
  {
    name: "Huggingface",
    id: "huggingface",
    category: "AI & Data Science",
    field: "AI",
    level: "advanced",
    href: "https://huggingface.co/",
  },
  // {
  //   name: 'GoLang',
  //   id: 'golang',
  //   category: 'Languages',
  //   level: 'learning',
  // },
  // {
  //   name: 'Jira',
  //   id: 'jira',
  //   category: 'DevOps & Tools',
  //   field: 'DevOps & Tools',
  //   subfield: 'Fullstack',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Sanity',
  //   id: 'sanity',
  //   category: 'Web Dev',
  //   field: 'CMS',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Pinecone',
  //   id: 'pinecone',
  //   category: 'AI & Data Science',
  //   field: 'AI',
  //   subfield: 'Vectors',
  //   level: 'advanced',
  // },
  // {
  //   name: 'TestRail',
  //   id: 'testrail',
  //   category: 'DevOps & Tools',
  //   field: 'DevOps & Tools',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Locust',
  //   id: 'locust',
  //   category: 'DevOps & Tools',
  //   field: 'DevOps & Tools',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Grafana',
  //   id: 'grafana',
  //   category: 'DevOps & Tools',
  //   field: 'DevOps & Tools',
  //   subfield: 'Fullstack',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Selenium',
  //   id: 'selenium',
  //   category: 'DevOps & Tools',
  //   field: 'DevOps & Tools',
  //   level: 'advanced',
  // },
  // {
  //   name: 'PyTest',
  //   id: 'pytest',
  //   category: 'DevOps & Tools',
  //   field: 'DevOps & Tools',
  //   level: 'advanced',
  // },
  // {
  //   name: 'Svelte',
  //   id: 'svelte',
  //   category: 'Web Dev',
  //   field: 'Frontend',
  //   subfield: 'Fullstack',
  //   level: 'advanced',
  // },
  // {
  //   name: 'SvelteKit',
  //   id: 'sveltekit',
  //   category: 'Web Dev',
  //   field: 'Fullstack',
  //   level: 'advanced',
  // },
  {
    name: "Vite",
    id: "vite",
    category: "Web Dev",
    field: "Fullstack",
    level: "advanced",
    mostUsed: true,
    href: "https://vitejs.dev/",
  },
  {
    name: "Tableau",
    id: "tableau",
    category: "AI & Data Science",
    field: "Analytics",
    level: "advanced",
    href: "https://www.tableau.com/",
  },
  {
    name: "Three.js",
    id: "threejs",
    category: "Web Dev",
    field: "Frontend",
    level: "learning",
    href: "https://threejs.org/",
  },
  //   {
  //     name: "Github Actions",
  //     id: "githubactions",
  //     category: "DevOps & Tools",
  //     field: "Deployment",
  //     level: "advanced",
  //   },
  {
    name: "Framer Motion",
    id: "framermotion",
    category: "Web Dev",
    field: "Frontend",
    level: "learning",
    href: "https://www.framer.com/motion/",
  },
  {
    name: "VS Code",
    id: "vscode",
    category: "DevOps & Tools",
    field: "Tools",
    level: "advanced",
    href: "https://code.visualstudio.com/",
  },
  //   {
  //     name: "MeiliSearch",
  //     id: "meilisearch",
  //     category: "Web Dev",
  //     field: "Backend",
  //     level: "advanced",
  //   },
  //   {
  //     name: "Stripe",
  //     id: "stripe",
  //     category: "Web Dev",
  //     field: "Backend",
  //     level: "advanced",
  //   },
  //   {
  //     name: "Notion",
  //     id: "notion",
  //     category: "DevOps & Tools",
  //     field: "Tools",
  //     level: "advanced",
  //   },
];

export const experienceData = [
  {
    name: "NTWIST",
    location: "Hybrid - Hyderabad, India",
    fallBack: "NT",
    description:
      "Ntwist provides data-powered solutions for industrial excellence, focusing on sustainability, mineral processing, mine-to-mill optimization, and oil & gas.",
    imgSrc:
      "https://ntwist.com/wp-content/uploads/2021/12/ntwist-logo-dark.png",
    url: "https://ntwist.com/",
    active: true,
    items: [
      {
        title: "Full Stack Developer - MERN",
        roleType: "Fulltime",
        startDate: "2024/08/08",
        year: "2024",
        description:
          "Implemented new features and fixed bugs, ensuring the continuous improvement and reliability of the software. Maintained server configurations, ensuring optimal performance and availability. Attended product meetings to ideate and discuss feature enhancements, contributing to the strategic growth and development of the software. Collaborated closely with cross-functional teams to ensure the alignment of development efforts with business goals and user needs. Developing prototypes for new features to be integrated within the software.",
        techStack: [
          { name: "React", href: "https://react.dev/" },
          { name: "Vite", href: "https://vite.dev/" },
          { name: "NodeJs", href: "https://nodejs.org/en" },
          { name: "Mongodb", href: "https://www.mongodb.com/" },
          { name: "Git", href: "https://git-scm.com/" },
          { name: "ShadCn", href: "https://ui.shadcn.com/" },
          { name: "Tailwind", href: "https://tailwindcss.com/" },
          { name: "Plotly", href: "https://plotly.com/" },
          { name: "Postman", href: "https://www.postman.com/" },
          { name: "Azure", href: "https://portal.azure.com/" },
        ],
      },
    ],
  },
  {
    name: "Pragmatiq Systems",
    location: "Onsite - Hyderabad, India",
    fallBack: "PS",
    description:
      "Sustainable technology company, Venturing cutting-edge solutions in the realms of Healthcare, Education, Agriculture & Life Sciences.",
    imgSrc:
      "https://pragmatiq.in/static/media/pragmatiq-01.61e60514f67419232e3a.png",
    url: "https://pragmatiq.in/",
    items: [
      {
        title: "Full Stack Developer (Intern)",
        roleType: "Fulltime",
        startDate: "2023/09/04",
        endDate: "2023/12/04",
        year: "Late 2023",
        description:
          "Developed responsive websites with React.js, Tailwind CSS and Styled Components. Implemented Node.js for backend, focusing on email functionality. Led the development and deployment of the web application, handling frontend, backend and deployment.",
        techStack: [
          { name: "React", href: "https://react.dev/" },
          { name: "Vite", href: "https://vite.dev/" },
          { name: "NextJs", href: "https://nextjs.org/" },
          { name: "NodeJs", href: "https://nodejs.org/en" },
          { name: "Mongodb", href: "https://www.mongodb.com/" },
          { name: "Git", href: "https://git-scm.com/" },
          { name: "ShadCn", href: "https://ui.shadcn.com/" },
          { name: "Tailwind", href: "https://tailwindcss.com/" },
          { name: "Plotly", href: "https://plotly.com/" },
          { name: "Postman", href: "https://www.postman.com/" },
          { name: "Postgres", href: "https://www.postgresql.org/" },
          { name: "AWS", href: "https://aws.amazon.com/" },
          { name: "github", href: "https://github.com/" },
          { name: "nginx", href: "https://www.nginx.com/" },
        ],
      },
    ],
  },
];

export const siteMetadata = {
  title: "Gowtham Nandavarapu",
  author: "Gowtham Nandavarapu",
  headerTitle: "Gowtham Nandavarapu",
  description: `An over-engineered personal blog where I write about software engineering, productivity, and other stupid stuff. Also, it's my portfolio.`,
  language: "en-us",
  theme: "dark", // system, dark or light
  siteRepo: "https://github.com/Gowtham242529/portfolio",
  siteLogo: "/static/images/site/logo.png",
  // mastodon: 'https://mastodon.social/@mastodonuser',
  email: "nandavarapugowtham3669@gmail.com",
  github: "https://github.com/Gowtham242529",
  x: "https://twitter.com/AndrewSamh",
  twitter: "https://twitter.com/AndrewSamh",
  // facebook: 'https://facebook.com',
  // youtube: 'https://youtube.com',
  linkedin: "https://www.linkedin.com/in/nandavarapu-gowtham-1403341b4/",
  // threads: 'https://www.threads.net',
  instagram: "https://www.instagram.com/_unique_be_blessed_/",
  spotify: "https://open.spotify.com/user/31enockcqxscwkxk7nymgltbvk54",
  // buymeacoffee: 'https://buymeacoffee.com/andrewsameh',
};

export const gitHubUsername = "Gowtham242529";

export const projectsData = [
  {
    type: "work",
    title: "Pragmatiq Systems",
    description:
      "Pragmatiq is a forward-thinking IT solutions company dedicated to sustainable technology. They deliver innovative solutions across Healthcare, Education, Agriculture, and Life Sciences, focusing on impactful advancements that address industry-specific needs through cutting-edge technologies.",
    imgSrc: "/pragmatiqSystems.png",
    builtWith: [
      { name: "React.js", url: "https://react.dev/" },
      { name: "OpenAI GPT-3.5", url: "https://openai.com/" },
      { name: "Tailwind CSS", url: "https://tailwindcss.com/" },
      { name: "Styled Components", url: "https://styled-components.com/" },
      { name: "Node.js", url: "https://nodejs.org/en" },
      { name: "Nodemailer", url: "https://nodemailer.com/about/" },
    ],
    url: "https://pragmatiq.in/",
  },
  {
    type: "work",
    title: "Purplegene",
    description:
      "Purplegene offers specialized training in various IT fields, providing individuals with essential skills for today's technology-driven landscape. Their focused programs are designed to equip learners with practical knowledge and industry-relevant expertise. - ( Developed user-friendly landing page)",
    imgSrc: "/purplegene.png",
    builtWith: [
      { name: "React.js", url: "https://react.dev/" },
      { name: "Material UI", url: "https://mui.com/material-ui/" },
    ],
    url: "https://purplegene.in/",
  },
  {
    type: "work",
    title: "ClinAlly mPower Health",
    description:
      "ClinAlly mPower Health is a healthcare application that leverages ABHA services for seamless doctor-patient monitoring. I developed key components, including the authentication screen, navigation panel, home screen, and screens for Appointments and Patients, enhancing user experience and navigation across the platform.",
    imgSrc: "/mPowerHealth.png",
    builtWith: [
      { name: "React.js", url: "https://react.dev/" },
      { name: "Material UI", url: "https://mui.com/material-ui/" },
      { name: "Node.js", url: "https://nodejs.org/en" },
      {
        name: "MSSQL",
        url: "https://www.microsoft.com/en-in/sql-server/sql-server-downloads",
      },
    ],
  },
  {
    type: "self",
    title: "Zoom Clone",
    imgSrc: "/zoomClone.png",
    description:
      "I developed a Zoom Clone using Next.js, creating a real-time video and audio meeting platform. This project replicates core video conferencing features, ensuring seamless connectivity and user-friendly interaction for virtual meetings.",
    repo: {
      name: "Zoom Clone",
      url: "https://github.com/Gowtham242529/zoom_clone",
      languages: ["JavaScript"],
      color: "yellow",
      homepageUrl: "https://zoom-clone-three-phi.vercel.app/",
    },
    builtWith: [
      { name: "Next.js", url: "https://nextjs.org/" },
      { name: "Tailwind CSS", url: "https://tailwindcss.com/" },
      { name: "Shadcn", url: "https://ui.shadcn.com/" },
      { name: "Clerk", url: "https://clerk.com/" },
      { name: "Stream", url: "https://getstream.io/" },
    ],
  },
  {
    type: "self",
    title: "Portfolio",
    imgSrc: "/portfolio.png",
    description:
      "It's my Portfolio where I showcase all the stupid stuff I do.",
    repo: {
      name: "Portfolio",
      url: "https://github.com/Gowtham242529/portfolio",
      languages: ["JavaScript"],
      color: "yellow",
      homepageUrl: "/",
    },
    builtWith: [
      { name: "Vite.js", url: "https://vitejs.dev/" },
      { name: "Tailwind CSS", url: "https://tailwindcss.com/" },
      { name: "Shadcn", url: "https://ui.shadcn.com/" },
      { name: "Magic UI", url: "https://magicui.design/" },
      { name: "Aceternity UI", url: "https://ui.aceternity.com/" },
      { name: "Framer Motion", url: "https://www.framer.com/" },
    ],
  },
];

export const aboutData = {
  name: "Gowtham Nandavarapu",
  occupation: "Full Stack Developer",
  company: "NTWIST",
  avatar: "/profilePic.jpg",
  email: "nandavarapugowtham3669@gmail.com",
  github: "https://github.com/Gowtham242529",
  linkedin: "https://www.linkedin.com/in/nandavarapu-gowtham-1403341b4/",
  instagram: "https://www.instagram.com/_unique_be_blessed_/",
  spotify: "https://open.spotify.com/user/31enockcqxscwkxk7nymgltbvk54",
  title: "Hi &#128075; I'm Gowtham Nandavarapu",
  description: [
    "I'm a Full Stack Developer &#128187; based in India. With a knack for Web Development, I love crafting innovative solutions that boost efficiency and performance. My tech journey has me building Responsive-driven applications, microservices, and full-stack solutions that push the envelope of possibility. My academic adventure includes a  Master's degree &#127891; and a Bachelor's degree &#127891; in Computer Science.",
    "Right now, I work hybrid &#127757; for NTWIST in Hyderabad, TG, India. I'm all about creating cool User Interface features and developing solid backend systems. Whether it's writing code or collaborating with cross-functional teams, I ensure our products meet top standards and our users.",
    "When I'm not coding, you'll find me grooving to my favorite Music &#127911; or Exploring 🧳 ( Can be Travelling or Learning ). These hobbies keep my creativity flowing and my mind fresh.",
    "🤖 I'm currently diving deep into Animations and 3D concepts, mastering Python, and exploring the Docker. Continuous learning is my passion, and I'm always on the lookout for the next big thing in tech.",
  ],
};

export const resumeData = {
  personalInfo: [
    {
      name: "Gowtham Nandavarapu",
      navLink: "gowtham-nandavarapu",
      data: [
        {
          data: "Full Stack Developer | React Developer | Backend Developer",
        },
      ],
    },
    {
      name: "Summary",
      navLink: "summary",
      data: [
        {
          data: "Experienced Software Developer with a strong background in Data Science, Web Development, and DevOps. Skilled in JavaScript and Python with expertise in frameworks & libraries such as React.js, Vite.js, and Next.js. know about cloud services like AWS and Azure, and well-versed in both SQL and NoSQL databases. Adept at developing Efficient-driven solutions and integrating machine learning models into applications. Proven track record in enhancing operational efficiency and customer service through innovative User Interface features.",
        },
      ],
    },
    {
      name: "Personal Information",
      navLink: "personal-info",
      data: [
        {
          name: "Languages",
          data: "Telugu [Native], English & Hindi",
        },
        {
          name: "hobbies",
          data: "Music, Exploring (Travelling or Learing)",
        },
      ],
    },
    {
      name: "Contact",
      navLink: "contact",
      data: [
        {
          name: "Phone",
          data: "+917287092388",
        },
        {
          name: "Email",
          data: "nandavarapugowtham3669@gmail.com",
        },
        {
          name: "LinkedIn",
          data: "https://www.linkedin.com/in/nandavarapu-gowtham-1403341b4/",
        },
        {
          name: "Instagram",
          data: "https://www.instagram.com/_unique_be_blessed_/",
        },
      ],
    },
  ],
  areasOfExpertise: {
    name: "Areas Of Expertise",
    navLink: "areas-of-expertise",
    data: [
      {
        name: "Languages",
        data: "JavaScript, Python, TypeScript, C",
      },
      {
        name: "Web Development",
        data: "React.js, Vite.js, Next.js, Node.js, Express.js, Tailwind CSS, Shadcn, MongoDB, MSSQL, MySql, PostgreSql, BootStrap, Framer Motion",
      },
      {
        name: "AI & Data Science",
        data: "Open AI, Pandas, Numpy, Anaconda, Jupyter Notebook, Matplotlib, Plotly, PowerBi, Hugging Face, Tableau",
      },
      {
        name: "DevOps & Tools",
        data: "AWS, Azure, Docker, Git, GitHub, VS Code, Postman, Vercel",
      },
    ],
  },
  professionalExperience: {
    name: "Professional Experience",
    navLink: "professional-experience",
    data: [
      {
        company: "NTWIST",
        navLink: "ntwist",
        location: "Hybrid - Hyderabad, India",
        title: "Full Stack Developer - MERN",
        roleType: "Fulltime",
        year: "2024/08/08 - Present",
        description:
          "Implemented new features and fixed bugs, ensuring the continuous improvement and reliability of the software. Maintained server configurations, ensuring optimal performance and availability. Attended product meetings to ideate and discuss feature enhancements, contributing to the strategic growth and development of the software. Collaborated closely with cross-functional teams to ensure the alignment of development efforts with business goals and user needs. Developing prototypes for new features to be integrated within the software.",
        techStack: [
          { name: "react", href: "https://react.dev/" },
          { name: "vite", href: "https://vite.dev/" },
          { name: "nodejs", href: "https://nodejs.org/en" },
          { name: "mongodb", href: "https://www.mongodb.com/" },
          { name: "git", href: "https://git-scm.com/" },
          { name: "github", href: "https://github.com/" },
          { name: "shadcn", href: "https://ui.shadcn.com/" },
          { name: "tailwind", href: "https://tailwindcss.com/" },
          { name: "plotly", href: "https://plotly.com/" },
          { name: "postman", href: "https://www.postman.com/" },
          { name: "azure", href: "https://portal.azure.com/" },
        ],
      },
      {
        company: "Pragmatiq Systems",
        navLink: "pragmatiq-systems",
        location: "Onsite - Hyderabad, India",
        title: "Full Stack Developer (Intern)",
        roleType: "Fulltime",
        year: "2023/09/04 - 2023/12/04",
        description:
          "Developed responsive websites with React.js, Tailwind CSS and Styled Components. Implemented Node.js for backend, focusing on email functionality. Led the development and deployment of the web application, handling frontend, backend and deployment.",
        techStack: [
          { name: "react", href: "https://react.dev/" },
          { name: "vite", href: "https://vite.dev/" },
          { name: "nextjs", href: "https://nextjs.org/" },
          { name: "nodejs", href: "https://nodejs.org/en" },
          { name: "mongodb", href: "https://www.mongodb.com/" },
          { name: "git", href: "https://git-scm.com/" },
          { name: "tailwind", href: "https://tailwindcss.com/" },
          { name: "postman", href: "https://www.postman.com/" },
          { name: "postgres", href: "https://www.postgresql.org/" },
          { name: "aws", href: "https://aws.amazon.com/" },
          { name: "github", href: "https://github.com/" },
          { name: "nginx", href: "https://www.nginx.com/" },
        ],
      },
    ],
  },
  education: {
    name: "Education",
    navLink: "education",
    data: [
      {
        degree: "Master of Sciences in Computer Science",
        institution: "PB Siddhartha College of Arts & Science",
        location: "Vijayawada, AP - India",
        year: "2022-2024",
        description:
          "Completed a 2-year postgraduate programe in Computer Science. Coursework included Data Science, Machine Learning, Data Visualization, and Web Development.",
      },
      {
        degree: "Bachelor of Sciences in Computer Science",
        institution: "Sir CR Reddy Degree College",
        location: "Eluru, AP - India",
        year: "2018-2022",
        description:
          "Completed a 3-year undergraduate program in Computer Science. Coursework included Data Structures, Algorithms, Computer Networks, Database Systems, and Web Development.",
      },
    ],
  },
  projects: {
    name: "Projects",
    navLink: "projects",
    data: [
      {
        name: "Pragmatiq Systems",
        navLink: "pragmatiq-systems-website",
        description:
          "Pragmatiq is a forward-thinking IT solutions company dedicated to sustainable technology. They deliver innovative solutions across Healthcare, Education, Agriculture, and Life Sciences, focusing on impactful advancements that address industry-specific needs through cutting-edge technologies.",
        builtWith: [
          { name: "React.js", url: "https://react.dev/" },
          { name: "OpenAI GPT-3.5", url: "https://openai.com/" },
          { name: "Tailwind CSS", url: "https://tailwindcss.com/" },
          {
            name: "Styled Components",
            url: "https://styled-components.com/",
          },
          { name: "Node.js", url: "https://nodejs.org/en" },
          { name: "Nodemailer", url: "https://nodemailer.com/about/" },
        ],
        url: "https://pragmatiq.in/",
      },
      {
        name: "Purplegene",
        navLink: "purplegene-website",
        description:
          "Purplegene offers specialized training in various IT fields, providing individuals with essential skills for today's technology-driven landscape. Their focused programs are designed to equip learners with practical knowledge and industry-relevant expertise. - (Developed user-friendly landing page)",
        builtWith: [
          { name: "React.js", url: "https://react.dev/" },
          { name: "Material UI", url: "https://mui.com/material-ui/" },
        ],
        url: "https://purplegene.in/",
      },
      {
        name: "ClinAlly mPower Health",
        navLink: "clinally-mpower-health-website",
        description:
          "ClinAlly mPower Health is a healthcare application that leverages ABHA services for seamless doctor-patient monitoring. I developed key components, including the authentication screen, navigation panel, home screen, and screens for Appointments and Patients, enhancing user experience and navigation across the platform.",
        imgSrc: "/mPowerHealth.png",
        builtWith: [
          { name: "React.js", url: "https://react.dev/" },
          { name: "Material UI", url: "https://mui.com/material-ui/" },
          { name: "Node.js", url: "https://nodejs.org/en" },
          {
            name: "MSSQL",
            url: "https://www.microsoft.com/en-in/sql-server/sql-server-downloads",
          },
        ],
      },
      {
        name: "Zoom Clone",
        navLink: "zoom-clone-website",
        description:
          "I developed a Zoom Clone using Next.js, creating a real-time video and audio meeting platform. This project replicates core video conferencing features, ensuring seamless connectivity and user-friendly interaction for virtual meetings.",
        imgSrc: "/zoomClone.png",
        repo: {
          name: "Zoom Clone",
          url: "https://github.com/Gowtham242529/zoom_clone",
          languages: ["JavaScript"],
          color: "yellow",
          homepageUrl: "https://zoom-clone-three-phi.vercel.app/",
        },
        builtWith: [
          { name: "Next.js", url: "https://nextjs.org/" },
          { name: "Tailwind CSS", url: "https://tailwindcss.com/" },
          { name: "Shadcn", url: "https://ui.shadcn.com/" },
          { name: "Clerk", url: "https://clerk.com/" },
          { name: "Stream", url: "https://getstream.io/" },
        ],
      },
      {
        name: "Portfolio",
        navLink: "portfolio-website",
        description:
          "It's my Portfolio where I showcase all the stupid stuff I do.",
        imgSrc: "/portfolio.png",
        repo: {
          name: "Portfolio",
          url: "https://github.com/Gowtham242529/portfolio",
          languages: ["JavaScript"],
          color: "yellow",
          homepageUrl: "https://zoom-clone-three-phi.vercel.app/",
        },
        builtWith: [
          { name: "Vite.js", url: "https://vitejs.dev/" },
          { name: "Tailwind CSS", url: "https://tailwindcss.com/" },
          { name: "Shadcn", url: "https://ui.shadcn.com/" },
          { name: "Magic UI", url: "https://magicui.design/" },
          { name: "Aceternity UI", url: "https://ui.aceternity.com/" },
          { name: "Framer Motion", url: "https://www.framer.com/" },
        ],
      },
    ],
  },
  navLinks: [
    "gowtham-nandavarapu",
    "summary",
    "personal-information",
    "contact",
    "areas-of-expertise",
    "professional-experience",
    "ntwist",
    "pragmatiq-systems",
    "education",
    "projects",
    "pragmatiq-systems-website",
    "purplegene-website",
    "clinally-mpower-health-website",
    "zoom-clone-website",
    "portfolio-website",
  ],
  navNames: [
    "Gowtham Nandavarapu",
    "Summary",
    "Personal Information",
    "Contact",
    "Areas Of Expertise",
    "Professional Experience",
    "NTWIST",
    "Pragmatiq Systems",
    "Education",
    "Projects",
    "Pragmatiq Systems",
    "Purplegene Website",
    "Clinally mpower Health",
    "Zoom Clone",
    "Portfolio",
  ],
};
